/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAlertsRouteImport } from './routes/api/public/alerts'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicAlertsIdRouteImport } from './routes/api/public/alerts.$id'
import { Route as ApiPublicDeviceDataRouteImport } from './routes/api/public/device/data'
import { Route as ApiPublicSensorsDataRouteImport } from './routes/api/public/sensors/data'
import { Route as ApiPublicSensorsHistoryRouteImport } from './routes/api/public/sensors/history'
import { Route as ApiPublicSensorsLatestRouteImport } from './routes/api/public/sensors/latest'
import { Route as ApiPublicTestSensorDataRouteImport } from './routes/api/public/test/sensor-data'
import { Route as ApiPublicDeviceStatusDeviceIdRouteImport } from './routes/api/public/device/status.$deviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsRoute = ApiPublicAlertsRouteImport.update({
  id: '/api/public/alerts',
  path: '/api/public/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsIdRoute = ApiPublicAlertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicAlertsRoute,
} as any)
const ApiPublicDeviceDataRoute = ApiPublicDeviceDataRouteImport.update({
  id: '/api/public/device/data',
  path: '/api/public/device/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSensorsDataRoute = ApiPublicSensorsDataRouteImport.update({
  id: '/api/public/sensors/data',
  path: '/api/public/sensors/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSensorsHistoryRoute = ApiPublicSensorsHistoryRouteImport.update({
  id: '/api/public/sensors/history',
  path: '/api/public/sensors/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSensorsLatestRoute = ApiPublicSensorsLatestRouteImport.update({
  id: '/api/public/sensors/latest',
  path: '/api/public/sensors/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestSensorDataRoute = ApiPublicTestSensorDataRouteImport.update({
  id: '/api/public/test/sensor-data',
  path: '/api/public/test/sensor-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceStatusDeviceIdRoute =
  ApiPublicDeviceStatusDeviceIdRouteImport.update({
    id: '/api/public/device/status/$deviceId',
    path: '/api/public/device/status/$deviceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/alerts/$id': typeof ApiPublicAlertsIdRoute
  '/api/public/device/data': typeof ApiPublicDeviceDataRoute
  '/api/public/sensors/data': typeof ApiPublicSensorsDataRoute
  '/api/public/sensors/history': typeof ApiPublicSensorsHistoryRoute
  '/api/public/sensors/latest': typeof ApiPublicSensorsLatestRoute
  '/api/public/test/sensor-data': typeof ApiPublicTestSensorDataRoute
  '/api/public/device/status/$deviceId': typeof ApiPublicDeviceStatusDeviceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/alerts/$id': typeof ApiPublicAlertsIdRoute
  '/api/public/device/data': typeof ApiPublicDeviceDataRoute
  '/api/public/sensors/data': typeof ApiPublicSensorsDataRoute
  '/api/public/sensors/history': typeof ApiPublicSensorsHistoryRoute
  '/api/public/sensors/latest': typeof ApiPublicSensorsLatestRoute
  '/api/public/test/sensor-data': typeof ApiPublicTestSensorDataRoute
  '/api/public/device/status/$deviceId': typeof ApiPublicDeviceStatusDeviceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/alerts/$id': typeof ApiPublicAlertsIdRoute
  '/api/public/device/data': typeof ApiPublicDeviceDataRoute
  '/api/public/sensors/data': typeof ApiPublicSensorsDataRoute
  '/api/public/sensors/history': typeof ApiPublicSensorsHistoryRoute
  '/api/public/sensors/latest': typeof ApiPublicSensorsLatestRoute
  '/api/public/test/sensor-data': typeof ApiPublicTestSensorDataRoute
  '/api/public/device/status/$deviceId': typeof ApiPublicDeviceStatusDeviceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/alerts'
    | '/api/public/health'
    | '/api/public/alerts/$id'
    | '/api/public/device/data'
    | '/api/public/sensors/data'
    | '/api/public/sensors/history'
    | '/api/public/sensors/latest'
    | '/api/public/test/sensor-data'
    | '/api/public/device/status/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/alerts'
    | '/api/public/health'
    | '/api/public/alerts/$id'
    | '/api/public/device/data'
    | '/api/public/sensors/data'
    | '/api/public/sensors/history'
    | '/api/public/sensors/latest'
    | '/api/public/test/sensor-data'
    | '/api/public/device/status/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/api/public/alerts'
    | '/api/public/health'
    | '/api/public/alerts/$id'
    | '/api/public/device/data'
    | '/api/public/sensors/data'
    | '/api/public/sensors/history'
    | '/api/public/sensors/latest'
    | '/api/public/test/sensor-data'
    | '/api/public/device/status/$deviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAlertsRoute: typeof ApiPublicAlertsRouteWithChildren
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicDeviceDataRoute: typeof ApiPublicDeviceDataRoute
  ApiPublicSensorsDataRoute: typeof ApiPublicSensorsDataRoute
  ApiPublicSensorsHistoryRoute: typeof ApiPublicSensorsHistoryRoute
  ApiPublicSensorsLatestRoute: typeof ApiPublicSensorsLatestRoute
  ApiPublicTestSensorDataRoute: typeof ApiPublicTestSensorDataRoute
  ApiPublicDeviceStatusDeviceIdRoute: typeof ApiPublicDeviceStatusDeviceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts': {
      id: '/api/public/alerts'
      path: '/api/public/alerts'
      fullPath: '/api/public/alerts'
      preLoaderRoute: typeof ApiPublicAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts/$id': {
      id: '/api/public/alerts/$id'
      path: '/$id'
      fullPath: '/api/public/alerts/$id'
      preLoaderRoute: typeof ApiPublicAlertsIdRouteImport
      parentRoute: typeof ApiPublicAlertsRoute
    }
    '/api/public/device/data': {
      id: '/api/public/device/data'
      path: '/api/public/device/data'
      fullPath: '/api/public/device/data'
      preLoaderRoute: typeof ApiPublicDeviceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sensors/data': {
      id: '/api/public/sensors/data'
      path: '/api/public/sensors/data'
      fullPath: '/api/public/sensors/data'
      preLoaderRoute: typeof ApiPublicSensorsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sensors/history': {
      id: '/api/public/sensors/history'
      path: '/api/public/sensors/history'
      fullPath: '/api/public/sensors/history'
      preLoaderRoute: typeof ApiPublicSensorsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sensors/latest': {
      id: '/api/public/sensors/latest'
      path: '/api/public/sensors/latest'
      fullPath: '/api/public/sensors/latest'
      preLoaderRoute: typeof ApiPublicSensorsLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test/sensor-data': {
      id: '/api/public/test/sensor-data'
      path: '/api/public/test/sensor-data'
      fullPath: '/api/public/test/sensor-data'
      preLoaderRoute: typeof ApiPublicTestSensorDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/status/$deviceId': {
      id: '/api/public/device/status/$deviceId'
      path: '/api/public/device/status/$deviceId'
      fullPath: '/api/public/device/status/$deviceId'
      preLoaderRoute: typeof ApiPublicDeviceStatusDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicAlertsRouteChildren {
  ApiPublicAlertsIdRoute: typeof ApiPublicAlertsIdRoute
}

const ApiPublicAlertsRouteChildren: ApiPublicAlertsRouteChildren = {
  ApiPublicAlertsIdRoute: ApiPublicAlertsIdRoute,
}

const ApiPublicAlertsRouteWithChildren = ApiPublicAlertsRoute._addFileChildren(
  ApiPublicAlertsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAlertsRoute: ApiPublicAlertsRouteWithChildren,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicDeviceDataRoute: ApiPublicDeviceDataRoute,
  ApiPublicSensorsDataRoute: ApiPublicSensorsDataRoute,
  ApiPublicSensorsHistoryRoute: ApiPublicSensorsHistoryRoute,
  ApiPublicSensorsLatestRoute: ApiPublicSensorsLatestRoute,
  ApiPublicTestSensorDataRoute: ApiPublicTestSensorDataRoute,
  ApiPublicDeviceStatusDeviceIdRoute: ApiPublicDeviceStatusDeviceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
